name: opulent
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  get: ^4.7.1
  url_launcher: ^6.3.1
  http: ^1.3.0
  get_storage: ^2.1.1
  logger: ^2.5.0
  flutter_native_splash: ^2.4.4
  smooth_page_indicator: ^1.2.0+3
  iconsax: ^0.0.8
  carousel_slider: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.11.0
  lottie: ^3.3.1
  connectivity_plus: ^6.1.3
  firebase_storage: ^12.4.2
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/content/
    - assets/images/on_boarding_images/
    - assets/images/products/
    - assets/images/reviews/
    - assets/logos/
    - assets/icons/brands/
    - assets/icons/categories/
    - assets/icons/payment_methods/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/logos/logo_back_dark.png'